name: Actions
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  js-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      # For playwright
      - uses: microsoft/playwright-github-action@v1

      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.22.1
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            plugins/pnpm-lock.yaml

      - name: Install and test via PNPM
        run: |
          pnpm install
          pnpm test:ci
